  server:
    port:
      9000

  spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        routes:
          - id: productservice
            uri: http://localhost:9001
            predicates:
              - Path=/api/v1/products/**
            filter:
              - AuthFilter
          - id: userservice
            uri: http://localhost:9002
            predicates:
              - Path=/api/v1/users/**
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"


